#!/usr/bin/env bash

# script/clean: Remove all build artifacts and cached dependencies.

source "$(dirname "$0")/.config"

if [ "$1" != "-y" ]; then
    _warn "==> Aborting, run $SCRIPT_NAME with \"-y\" to confirm"
    exit 1
fi

if [ -d ".direnv" ]; then
    _message "==> Removing direnv cache…"
    rm -rf .direnv
fi

if [ -d "node_modules" ]; then
    _message "==> Removing node_modules…"
    rm -rf node_modules
fi

_message "==> Removing files in .gitignore…"
git clean -dfX -n

_message "==> Removing poetry environments…"
poetry env remove --all
