#!/usr/bin/env bash

# script/server: Launch {{ cookiecutter.project_slug }} and any extra required processes
#                locally.

source "$(dirname "$0")/.config"

# ensure everything in the app is up to date.
script/update || exit 1

poetry run python manage.py runserver
